# -*- coding: utf-8 -*-
"""proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JIQeycSvuavS8IhoDc8hxPQ3dabMsWI
"""

import numpy as np
import streamlit as st
import pandas as pd

st.write(''' # Predicción del Costo  ''')
st.image("gastos.jpg", caption="Predicción del Costo en función del Tipo de actividad y el Momento del día.")

st.header('Datos de la actividad')

def user_input_features():
  # Entrada
  Tipo = st.number_input('Tipo de actividad: (Transporte=0, Alimentos=1, Ocio=2, Ejercicio=3):', min_value=0, max_value=3, value = 0, step = 1)
  Momento = st.number_input('Momento del día (mañana=0, tarde=1, noche=2):',  min_value=0, max_value=2, value = 0, step = 1)

  user_input_data = = {
                        'Tipo': Tipo,
                        'Momento': Momento
                         }

  features = pd.DataFrame(user_input_data, index=[0])

  return features

df = user_input_features()

datos =  pd.read_csv('Optativafinal1.csv', encoding='latin-1')
X = [['Tipo', 'Momento']]
y = datos['Costo']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1613497)
LR = LinearRegression()
LR.fit(X_train,y_train)

b1 = LR.coef_
b0 = LR.intercept_
prediccion = b0 + b1[0] * df['Tipo'] + b1[1] * df['Momento']

st.subheader('Costo estimado')
st.write('El costo estimado es ', prediccion)