# -*- coding: utf-8 -*-
"""proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JIQeycSvuavS8IhoDc8hxPQ3dabMsWI
"""

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

st.write("# Predicción del Costo")
st.image("gastos.jpg", caption="Predicción del costo según tipo de actividad y momento del día.")

st.header("Ingresa los datos de la actividad")

def user_input_features():
    tipo = st.number_input(
        "Tipo de actividad (0=Transporte, 1=Alimentos, 2=Ocio, 3=Ejercicio, 4=Académico):",
        min_value=0, max_value=4, value=0, step=1
    )

    momento = st.number_input(
        "Momento (0=Tarde, 1=Mañana, 2=Noche):",
        min_value=0, max_value=2, value=0, step=1
    )

    features = pd.DataFrame({
        "Tipo": [tipo],
        "Momento": [momento]
    })

    return features

df_user = user_input_features()

df = pd.read_excel("Optativa_8.xlsx")

df.drop(columns=["Nombre actividad", "Presupuesto", "No. de personas",
                 "Tiempo invertido", "Número", "Fecha (dd/mm/aa)"],
        inplace=True)

df.replace({
    "Momento": {"tarde": 0, "manana": 1, "noche": 2},
    "Tipo": {"Transporte": 0, "Alimentos": 1, "Ocio": 2,
             "Ejercicio": 3, "Académico": 4}
}, inplace=True)

df.dropna(subset=["Tipo"], inplace=True)

X = df[["Tipo", "Momento"]]
y = df["Costo"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=1613497
)

LR = LinearRegression()
LR.fit(X_train, y_train)

prediccion = LR.predict(df_user)

st.subheader("Predicción del costo")
st.write(f"El costo estimado de la actividad es: **${prediccion[0]:.2f}**")